SRCS = FileList["**/*.java"]
OBJS = SRCS.ext('class')
CLASSDIR = "../webapps/WEB-INF/classes"
require 'fileutils'

task :default => "make"

rule '.class' => ['.java'] do |t|
    sh "javac #{t.source}"
    FileUtils.copy( t.name, File.join( CLASSDIR, t.name) )
    puts "deployed #{t.name} to #{File.join(CLASSDIR, t.name)}"
end

file "make" => OBJS do |t|
    sh "javac Main.java"
end

task :clean do
    Dir.glob('./**/*').each do |file|
        next if file !~ /\.class$/
        puts "delete #{file}"
        FileUtils.rm(file)
    end
end

task :deploy do
    Dir.glob('./**/*').each do |file|
        next if file !~ /\.class$/
        puts "deployed #{file} to #{File.join(CLASSDIR, file)}"
        FileUtils.copy( file, File.join(CLASSDIR, file) )
    end
end
