SRCS = FileList["**/*.java"]
OBJS = SRCS.ext('class')

desc "default"
task :default => "make"

task :make => OBJS do |t|
    sh "javac #{t.prerequisites.join(' ')}"
end

rule '.class' => '.java' do |t|
    sh "javac #{t.source}"
end
